title: "SquirrelGame.lt"
description: "Žaidimo puslapis"

# Use no theme (you have your own HTML/CSS)
theme: null

# Build output goes into docs/
destination: docs

# Important: don’t treat docs/ as source
exclude:
  - docs
  - Readme.md
  - Gemfile
  - Gemfile.lock
